import { WordEntry } from "../../../core/types";

/**
 * 内置词库种子数据
 *
 * 由于完整词库体积很大（CET4 4500 词 × 完整释义 ≈ 1MB），
 * 这里只内嵌每个词库的**核心高频词**（约 100-150 词）作为种子。
 * 用户可以通过「扩展词库」功能用 AI 补充更多。
 *
 * 实际生产可以替换为完整版。
 */
export const BUILTIN_VOCAB_DATA: Record<string, WordEntry[]> = {

  // ═══════════════════════════════════════════════════════
  // CET-4 高频核心 100 词
  // ═══════════════════════════════════════════════════════
  cet4: [
    { word: "abandon", phonetic: "/əˈbændən/", partOfSpeech: "v.", definitions: ["放弃", "抛弃"], examples: [{ en: "He abandoned his car in the snow.", cn: "他把车扔在雪地里。" }], frequency: 1, difficulty: 2 },
    { word: "ability", phonetic: "/əˈbɪləti/", partOfSpeech: "n.", definitions: ["能力", "才能"], frequency: 2, difficulty: 1 },
    { word: "absolute", phonetic: "/ˈæbsəluːt/", partOfSpeech: "adj.", definitions: ["绝对的", "完全的"], frequency: 3, difficulty: 2 },
    { word: "academic", phonetic: "/ˌækəˈdemɪk/", partOfSpeech: "adj.", definitions: ["学术的", "学院的"], frequency: 4, difficulty: 2 },
    { word: "accept", phonetic: "/əkˈsept/", partOfSpeech: "v.", definitions: ["接受", "认可"], frequency: 5, difficulty: 1 },
    { word: "access", phonetic: "/ˈækses/", partOfSpeech: "n./v.", definitions: ["进入", "访问"], frequency: 6, difficulty: 1 },
    { word: "accident", phonetic: "/ˈæksɪdənt/", partOfSpeech: "n.", definitions: ["事故", "意外"], frequency: 7, difficulty: 1 },
    { word: "according", phonetic: "/əˈkɔːrdɪŋ/", partOfSpeech: "adv.", definitions: ["根据", "按照"], frequency: 8, difficulty: 1 },
    { word: "achieve", phonetic: "/əˈtʃiːv/", partOfSpeech: "v.", definitions: ["实现", "达到"], frequency: 9, difficulty: 2 },
    { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", partOfSpeech: "v.", definitions: ["承认", "确认"], frequency: 10, difficulty: 3 },
    { word: "active", phonetic: "/ˈæktɪv/", partOfSpeech: "adj.", definitions: ["积极的", "活跃的"], frequency: 11, difficulty: 1 },
    { word: "activity", phonetic: "/ækˈtɪvəti/", partOfSpeech: "n.", definitions: ["活动", "活力"], frequency: 12, difficulty: 1 },
    { word: "actually", phonetic: "/ˈæktʃuəli/", partOfSpeech: "adv.", definitions: ["实际上", "事实上"], frequency: 13, difficulty: 1 },
    { word: "address", phonetic: "/əˈdres/", partOfSpeech: "n./v.", definitions: ["地址", "演说", "处理"], frequency: 14, difficulty: 1 },
    { word: "adjust", phonetic: "/əˈdʒʌst/", partOfSpeech: "v.", definitions: ["调整", "适应"], frequency: 15, difficulty: 2 },
    { word: "admit", phonetic: "/ədˈmɪt/", partOfSpeech: "v.", definitions: ["承认", "允许进入"], frequency: 16, difficulty: 2 },
    { word: "adopt", phonetic: "/əˈdɒpt/", partOfSpeech: "v.", definitions: ["采纳", "收养"], frequency: 17, difficulty: 2 },
    { word: "advance", phonetic: "/ədˈvɑːns/", partOfSpeech: "n./v.", definitions: ["前进", "进步"], frequency: 18, difficulty: 2 },
    { word: "advantage", phonetic: "/ədˈvɑːntɪdʒ/", partOfSpeech: "n.", definitions: ["优势", "好处"], frequency: 19, difficulty: 2 },
    { word: "affect", phonetic: "/əˈfekt/", partOfSpeech: "v.", definitions: ["影响", "感动"], frequency: 20, difficulty: 2 },
    { word: "afford", phonetic: "/əˈfɔːrd/", partOfSpeech: "v.", definitions: ["买得起", "负担得起"], frequency: 21, difficulty: 2 },
    { word: "agency", phonetic: "/ˈeɪdʒənsi/", partOfSpeech: "n.", definitions: ["机构", "代理"], frequency: 22, difficulty: 2 },
    { word: "agreement", phonetic: "/əˈɡriːmənt/", partOfSpeech: "n.", definitions: ["协议", "同意"], frequency: 23, difficulty: 2 },
    { word: "agriculture", phonetic: "/ˈæɡrɪkʌltʃər/", partOfSpeech: "n.", definitions: ["农业"], frequency: 24, difficulty: 2 },
    { word: "ahead", phonetic: "/əˈhed/", partOfSpeech: "adv.", definitions: ["在前面", "向前"], frequency: 25, difficulty: 1 },
    { word: "aim", phonetic: "/eɪm/", partOfSpeech: "n./v.", definitions: ["目的", "瞄准"], frequency: 26, difficulty: 1 },
    { word: "alarm", phonetic: "/əˈlɑːrm/", partOfSpeech: "n.", definitions: ["警报", "闹钟"], frequency: 27, difficulty: 2 },
    { word: "alcohol", phonetic: "/ˈælkəhɒl/", partOfSpeech: "n.", definitions: ["酒精", "酒"], frequency: 28, difficulty: 2 },
    { word: "alternative", phonetic: "/ɔːlˈtɜːrnətɪv/", partOfSpeech: "adj./n.", definitions: ["可选的", "替代品"], frequency: 29, difficulty: 3 },
    { word: "amazing", phonetic: "/əˈmeɪzɪŋ/", partOfSpeech: "adj.", definitions: ["惊人的", "令人惊讶的"], frequency: 30, difficulty: 1 },
    { word: "ambition", phonetic: "/æmˈbɪʃn/", partOfSpeech: "n.", definitions: ["野心", "抱负"], frequency: 31, difficulty: 2 },
    { word: "ancient", phonetic: "/ˈeɪnʃənt/", partOfSpeech: "adj.", definitions: ["古代的", "古老的"], frequency: 32, difficulty: 2 },
    { word: "announce", phonetic: "/əˈnaʊns/", partOfSpeech: "v.", definitions: ["宣布", "通告"], frequency: 33, difficulty: 2 },
    { word: "annual", phonetic: "/ˈænjuəl/", partOfSpeech: "adj.", definitions: ["每年的", "年度的"], frequency: 34, difficulty: 2 },
    { word: "anxious", phonetic: "/ˈæŋkʃəs/", partOfSpeech: "adj.", definitions: ["焦虑的", "担心的"], frequency: 35, difficulty: 2 },
    { word: "apparent", phonetic: "/əˈpærənt/", partOfSpeech: "adj.", definitions: ["明显的", "表面上的"], frequency: 36, difficulty: 3 },
    { word: "appeal", phonetic: "/əˈpiːl/", partOfSpeech: "n./v.", definitions: ["呼吁", "上诉", "吸引力"], frequency: 37, difficulty: 2 },
    { word: "appear", phonetic: "/əˈpɪər/", partOfSpeech: "v.", definitions: ["出现", "似乎"], frequency: 38, difficulty: 1 },
    { word: "apply", phonetic: "/əˈplaɪ/", partOfSpeech: "v.", definitions: ["申请", "应用"], frequency: 39, difficulty: 1 },
    { word: "appoint", phonetic: "/əˈpɔɪnt/", partOfSpeech: "v.", definitions: ["任命", "约定"], frequency: 40, difficulty: 2 },
    { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", partOfSpeech: "v.", definitions: ["欣赏", "感激"], frequency: 41, difficulty: 2 },
    { word: "approach", phonetic: "/əˈproʊtʃ/", partOfSpeech: "n./v.", definitions: ["接近", "方法"], frequency: 42, difficulty: 2 },
    { word: "appropriate", phonetic: "/əˈproʊpriət/", partOfSpeech: "adj.", definitions: ["合适的", "适当的"], frequency: 43, difficulty: 3 },
    { word: "approve", phonetic: "/əˈpruːv/", partOfSpeech: "v.", definitions: ["批准", "赞成"], frequency: 44, difficulty: 2 },
    { word: "argue", phonetic: "/ˈɑːrɡjuː/", partOfSpeech: "v.", definitions: ["争论", "主张"], frequency: 45, difficulty: 1 },
    { word: "arrange", phonetic: "/əˈreɪndʒ/", partOfSpeech: "v.", definitions: ["安排", "整理"], frequency: 46, difficulty: 2 },
    { word: "arrest", phonetic: "/əˈrest/", partOfSpeech: "v./n.", definitions: ["逮捕", "阻止"], frequency: 47, difficulty: 2 },
    { word: "artificial", phonetic: "/ˌɑːrtɪˈfɪʃl/", partOfSpeech: "adj.", definitions: ["人造的", "人工的"], frequency: 48, difficulty: 2 },
    { word: "aspect", phonetic: "/ˈæspekt/", partOfSpeech: "n.", definitions: ["方面", "外观"], frequency: 49, difficulty: 2 },
    { word: "assess", phonetic: "/əˈses/", partOfSpeech: "v.", definitions: ["评估", "估价"], frequency: 50, difficulty: 3 },
    { word: "assist", phonetic: "/əˈsɪst/", partOfSpeech: "v.", definitions: ["帮助", "协助"], frequency: 51, difficulty: 2 },
    { word: "associate", phonetic: "/əˈsoʊʃieɪt/", partOfSpeech: "v.", definitions: ["联系", "交往"], frequency: 52, difficulty: 2 },
    { word: "assume", phonetic: "/əˈsuːm/", partOfSpeech: "v.", definitions: ["假定", "承担"], frequency: 53, difficulty: 2 },
    { word: "attempt", phonetic: "/əˈtempt/", partOfSpeech: "n./v.", definitions: ["尝试", "试图"], frequency: 54, difficulty: 2 },
    { word: "attend", phonetic: "/əˈtend/", partOfSpeech: "v.", definitions: ["出席", "参加"], frequency: 55, difficulty: 1 },
    { word: "attention", phonetic: "/əˈtenʃn/", partOfSpeech: "n.", definitions: ["注意", "关注"], frequency: 56, difficulty: 1 },
    { word: "attitude", phonetic: "/ˈætɪtuːd/", partOfSpeech: "n.", definitions: ["态度", "看法"], frequency: 57, difficulty: 1 },
    { word: "attract", phonetic: "/əˈtrækt/", partOfSpeech: "v.", definitions: ["吸引", "引起"], frequency: 58, difficulty: 2 },
    { word: "audience", phonetic: "/ˈɔːdiəns/", partOfSpeech: "n.", definitions: ["观众", "听众"], frequency: 59, difficulty: 2 },
    { word: "authority", phonetic: "/əˈθɔːrəti/", partOfSpeech: "n.", definitions: ["权威", "当局"], frequency: 60, difficulty: 2 },
    { word: "available", phonetic: "/əˈveɪləbl/", partOfSpeech: "adj.", definitions: ["可用的", "有空的"], frequency: 61, difficulty: 2 },
    { word: "average", phonetic: "/ˈævərɪdʒ/", partOfSpeech: "adj./n.", definitions: ["平均的", "平均值"], frequency: 62, difficulty: 1 },
    { word: "avoid", phonetic: "/əˈvɔɪd/", partOfSpeech: "v.", definitions: ["避免", "回避"], frequency: 63, difficulty: 1 },
    { word: "aware", phonetic: "/əˈwer/", partOfSpeech: "adj.", definitions: ["意识到的", "知道的"], frequency: 64, difficulty: 2 },
    { word: "background", phonetic: "/ˈbækɡraʊnd/", partOfSpeech: "n.", definitions: ["背景", "出身"], frequency: 65, difficulty: 1 },
    { word: "balance", phonetic: "/ˈbæləns/", partOfSpeech: "n./v.", definitions: ["平衡", "余额"], frequency: 66, difficulty: 1 },
    { word: "barrier", phonetic: "/ˈbæriər/", partOfSpeech: "n.", definitions: ["障碍", "屏障"], frequency: 67, difficulty: 2 },
    { word: "basis", phonetic: "/ˈbeɪsɪs/", partOfSpeech: "n.", definitions: ["基础", "根据"], frequency: 68, difficulty: 2 },
    { word: "behavior", phonetic: "/bɪˈheɪvjər/", partOfSpeech: "n.", definitions: ["行为", "举止"], frequency: 69, difficulty: 1 },
    { word: "benefit", phonetic: "/ˈbenɪfɪt/", partOfSpeech: "n./v.", definitions: ["利益", "受益"], frequency: 70, difficulty: 2 },
    { word: "beyond", phonetic: "/biˈjɒnd/", partOfSpeech: "prep.", definitions: ["超越", "在...之外"], frequency: 71, difficulty: 2 },
    { word: "bind", phonetic: "/baɪnd/", partOfSpeech: "v.", definitions: ["捆绑", "约束"], frequency: 72, difficulty: 2 },
    { word: "blame", phonetic: "/bleɪm/", partOfSpeech: "v.", definitions: ["责备", "归咎于"], frequency: 73, difficulty: 2 },
    { word: "boost", phonetic: "/buːst/", partOfSpeech: "v./n.", definitions: ["促进", "推动"], frequency: 74, difficulty: 2 },
    { word: "border", phonetic: "/ˈbɔːrdər/", partOfSpeech: "n.", definitions: ["边界", "边境"], frequency: 75, difficulty: 1 },
    { word: "brand", phonetic: "/brænd/", partOfSpeech: "n.", definitions: ["品牌", "商标"], frequency: 76, difficulty: 1 },
    { word: "brief", phonetic: "/briːf/", partOfSpeech: "adj.", definitions: ["简短的", "简洁的"], frequency: 77, difficulty: 1 },
    { word: "broad", phonetic: "/brɔːd/", partOfSpeech: "adj.", definitions: ["宽阔的", "广泛的"], frequency: 78, difficulty: 1 },
    { word: "budget", phonetic: "/ˈbʌdʒɪt/", partOfSpeech: "n.", definitions: ["预算"], frequency: 79, difficulty: 2 },
    { word: "campaign", phonetic: "/kæmˈpeɪn/", partOfSpeech: "n.", definitions: ["运动", "战役"], frequency: 80, difficulty: 2 },
    { word: "capacity", phonetic: "/kəˈpæsəti/", partOfSpeech: "n.", definitions: ["容量", "能力"], frequency: 81, difficulty: 2 },
    { word: "capital", phonetic: "/ˈkæpɪtl/", partOfSpeech: "n.", definitions: ["首都", "资本"], frequency: 82, difficulty: 1 },
    { word: "career", phonetic: "/kəˈrɪər/", partOfSpeech: "n.", definitions: ["职业", "生涯"], frequency: 83, difficulty: 1 },
    { word: "category", phonetic: "/ˈkætəɡɔːri/", partOfSpeech: "n.", definitions: ["类别", "分类"], frequency: 84, difficulty: 2 },
    { word: "celebrate", phonetic: "/ˈselɪbreɪt/", partOfSpeech: "v.", definitions: ["庆祝", "颂扬"], frequency: 85, difficulty: 1 },
    { word: "challenge", phonetic: "/ˈtʃæləndʒ/", partOfSpeech: "n./v.", definitions: ["挑战", "质疑"], frequency: 86, difficulty: 2 },
    { word: "character", phonetic: "/ˈkærəktər/", partOfSpeech: "n.", definitions: ["性格", "角色"], frequency: 87, difficulty: 1 },
    { word: "charge", phonetic: "/tʃɑːrdʒ/", partOfSpeech: "v./n.", definitions: ["收费", "充电", "指控"], frequency: 88, difficulty: 1 },
    { word: "chief", phonetic: "/tʃiːf/", partOfSpeech: "adj./n.", definitions: ["主要的", "首领"], frequency: 89, difficulty: 1 },
    { word: "circumstance", phonetic: "/ˈsɜːrkəmstæns/", partOfSpeech: "n.", definitions: ["情况", "环境"], frequency: 90, difficulty: 3 },
    { word: "claim", phonetic: "/kleɪm/", partOfSpeech: "v./n.", definitions: ["声称", "索赔"], frequency: 91, difficulty: 2 },
    { word: "client", phonetic: "/ˈklaɪənt/", partOfSpeech: "n.", definitions: ["客户", "委托人"], frequency: 92, difficulty: 1 },
    { word: "combine", phonetic: "/kəmˈbaɪn/", partOfSpeech: "v.", definitions: ["结合", "联合"], frequency: 93, difficulty: 2 },
    { word: "commercial", phonetic: "/kəˈmɜːrʃl/", partOfSpeech: "adj.", definitions: ["商业的", "商务的"], frequency: 94, difficulty: 2 },
    { word: "commit", phonetic: "/kəˈmɪt/", partOfSpeech: "v.", definitions: ["承诺", "犯（罪）"], frequency: 95, difficulty: 2 },
    { word: "communicate", phonetic: "/kəˈmjuːnɪkeɪt/", partOfSpeech: "v.", definitions: ["沟通", "交流"], frequency: 96, difficulty: 2 },
    { word: "community", phonetic: "/kəˈmjuːnəti/", partOfSpeech: "n.", definitions: ["社区", "团体"], frequency: 97, difficulty: 1 },
    { word: "compete", phonetic: "/kəmˈpiːt/", partOfSpeech: "v.", definitions: ["竞争", "比赛"], frequency: 98, difficulty: 2 },
    { word: "complaint", phonetic: "/kəmˈpleɪnt/", partOfSpeech: "n.", definitions: ["抱怨", "投诉"], frequency: 99, difficulty: 2 },
    { word: "complete", phonetic: "/kəmˈpliːt/", partOfSpeech: "adj./v.", definitions: ["完成的", "完整的"], frequency: 100, difficulty: 1 },
  ],

  // ═══════════════════════════════════════════════════════
  // CET-6 高频核心 50 词（示例，可扩展）
  // ═══════════════════════════════════════════════════════
  cet6: [
    { word: "accommodate", phonetic: "/əˈkɒmədeɪt/", partOfSpeech: "v.", definitions: ["容纳", "适应"], frequency: 1, difficulty: 3 },
    { word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/", partOfSpeech: "v.", definitions: ["积累", "积聚"], frequency: 2, difficulty: 3 },
    { word: "accurate", phonetic: "/ˈækjərət/", partOfSpeech: "adj.", definitions: ["精确的", "准确的"], frequency: 3, difficulty: 2 },
    { word: "acquaintance", phonetic: "/əˈkweɪntəns/", partOfSpeech: "n.", definitions: ["熟人", "相识"], frequency: 4, difficulty: 3 },
    { word: "adequate", phonetic: "/ˈædɪkwət/", partOfSpeech: "adj.", definitions: ["充足的", "适当的"], frequency: 5, difficulty: 3 },
    { word: "advocate", phonetic: "/ˈædvəkeɪt/", partOfSpeech: "v./n.", definitions: ["拥护", "提倡者"], frequency: 6, difficulty: 3 },
    { word: "aesthetic", phonetic: "/iːsˈθetɪk/", partOfSpeech: "adj.", definitions: ["审美的", "美学的"], frequency: 7, difficulty: 4 },
    { word: "allocate", phonetic: "/ˈæləkeɪt/", partOfSpeech: "v.", definitions: ["分配", "分派"], frequency: 8, difficulty: 3 },
    { word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", partOfSpeech: "adj.", definitions: ["模糊的", "歧义的"], frequency: 9, difficulty: 4 },
    { word: "analogy", phonetic: "/əˈnælədʒi/", partOfSpeech: "n.", definitions: ["类比", "类似"], frequency: 10, difficulty: 3 },
    { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", partOfSpeech: "v.", definitions: ["预期", "预料"], frequency: 11, difficulty: 3 },
    { word: "arbitrary", phonetic: "/ˈɑːrbɪtreri/", partOfSpeech: "adj.", definitions: ["任意的", "专制的"], frequency: 12, difficulty: 4 },
    { word: "assemble", phonetic: "/əˈsembl/", partOfSpeech: "v.", definitions: ["集合", "组装"], frequency: 13, difficulty: 3 },
    { word: "assertion", phonetic: "/əˈsɜːrʃn/", partOfSpeech: "n.", definitions: ["主张", "断言"], frequency: 14, difficulty: 4 },
    { word: "autonomy", phonetic: "/ɔːˈtɒnəmi/", partOfSpeech: "n.", definitions: ["自治", "自主"], frequency: 15, difficulty: 4 },
    { word: "behalf", phonetic: "/bɪˈhæf/", partOfSpeech: "n.", definitions: ["代表", "利益"], frequency: 16, difficulty: 3 },
    { word: "bias", phonetic: "/ˈbaɪəs/", partOfSpeech: "n.", definitions: ["偏见", "偏向"], frequency: 17, difficulty: 3 },
    { word: "boundary", phonetic: "/ˈbaʊndri/", partOfSpeech: "n.", definitions: ["边界", "范围"], frequency: 18, difficulty: 2 },
    { word: "candidate", phonetic: "/ˈkændɪdət/", partOfSpeech: "n.", definitions: ["候选人", "应试者"], frequency: 19, difficulty: 2 },
    { word: "casualty", phonetic: "/ˈkæʒuəlti/", partOfSpeech: "n.", definitions: ["伤亡", "意外事故"], frequency: 20, difficulty: 4 },
    { word: "cease", phonetic: "/siːs/", partOfSpeech: "v.", definitions: ["停止", "结束"], frequency: 21, difficulty: 3 },
    { word: "cognitive", phonetic: "/ˈkɒɡnətɪv/", partOfSpeech: "adj.", definitions: ["认知的", "认识的"], frequency: 22, difficulty: 4 },
    { word: "coherent", phonetic: "/koʊˈhɪrənt/", partOfSpeech: "adj.", definitions: ["连贯的", "一致的"], frequency: 23, difficulty: 4 },
    { word: "compatible", phonetic: "/kəmˈpætəbl/", partOfSpeech: "adj.", definitions: ["兼容的", "相容的"], frequency: 24, difficulty: 3 },
    { word: "compensate", phonetic: "/ˈkɒmpenseɪt/", partOfSpeech: "v.", definitions: ["补偿", "弥补"], frequency: 25, difficulty: 3 },
    { word: "comprehensive", phonetic: "/ˌkɒmprɪˈhensɪv/", partOfSpeech: "adj.", definitions: ["全面的", "综合的"], frequency: 26, difficulty: 3 },
    { word: "consensus", phonetic: "/kənˈsensəs/", partOfSpeech: "n.", definitions: ["共识", "一致"], frequency: 27, difficulty: 4 },
    { word: "constraint", phonetic: "/kənˈstreɪnt/", partOfSpeech: "n.", definitions: ["约束", "限制"], frequency: 28, difficulty: 4 },
    { word: "contradict", phonetic: "/ˌkɒntrəˈdɪkt/", partOfSpeech: "v.", definitions: ["否认", "矛盾"], frequency: 29, difficulty: 3 },
    { word: "convention", phonetic: "/kənˈvenʃn/", partOfSpeech: "n.", definitions: ["惯例", "大会"], frequency: 30, difficulty: 3 },
    { word: "correlate", phonetic: "/ˈkɒrəleɪt/", partOfSpeech: "v.", definitions: ["相关", "关联"], frequency: 31, difficulty: 4 },
    { word: "credible", phonetic: "/ˈkredəbl/", partOfSpeech: "adj.", definitions: ["可信的", "可靠的"], frequency: 32, difficulty: 4 },
    { word: "criterion", phonetic: "/kraɪˈtɪriən/", partOfSpeech: "n.", definitions: ["标准", "准则"], frequency: 33, difficulty: 4 },
    { word: "cultivate", phonetic: "/ˈkʌltɪveɪt/", partOfSpeech: "v.", definitions: ["培养", "耕作"], frequency: 34, difficulty: 3 },
    { word: "deficit", phonetic: "/ˈdefɪsɪt/", partOfSpeech: "n.", definitions: ["赤字", "不足"], frequency: 35, difficulty: 4 },
    { word: "deliberately", phonetic: "/dɪˈlɪbərətli/", partOfSpeech: "adv.", definitions: ["故意地", "深思熟虑地"], frequency: 36, difficulty: 3 },
    { word: "discrimination", phonetic: "/dɪˌskrɪmɪˈneɪʃn/", partOfSpeech: "n.", definitions: ["歧视", "辨别"], frequency: 37, difficulty: 4 },
    { word: "diverse", phonetic: "/daɪˈvɜːrs/", partOfSpeech: "adj.", definitions: ["多样的", "不同的"], frequency: 38, difficulty: 3 },
    { word: "elaborate", phonetic: "/ɪˈlæbərət/", partOfSpeech: "adj./v.", definitions: ["详尽的", "详细说明"], frequency: 39, difficulty: 4 },
    { word: "embrace", phonetic: "/ɪmˈbreɪs/", partOfSpeech: "v.", definitions: ["拥抱", "采纳"], frequency: 40, difficulty: 3 },
    { word: "endorse", phonetic: "/ɪnˈdɔːrs/", partOfSpeech: "v.", definitions: ["支持", "背书"], frequency: 41, difficulty: 4 },
    { word: "enhance", phonetic: "/ɪnˈhæns/", partOfSpeech: "v.", definitions: ["提高", "增强"], frequency: 42, difficulty: 3 },
    { word: "evident", phonetic: "/ˈevɪdənt/", partOfSpeech: "adj.", definitions: ["明显的", "显然的"], frequency: 43, difficulty: 3 },
    { word: "exemplify", phonetic: "/ɪɡˈzemplɪfaɪ/", partOfSpeech: "v.", definitions: ["举例说明", "作为典范"], frequency: 44, difficulty: 4 },
    { word: "fabricate", phonetic: "/ˈfæbrɪkeɪt/", partOfSpeech: "v.", definitions: ["制造", "捏造"], frequency: 45, difficulty: 4 },
    { word: "feasible", phonetic: "/ˈfiːzəbl/", partOfSpeech: "adj.", definitions: ["可行的"], frequency: 46, difficulty: 4 },
    { word: "fluctuate", phonetic: "/ˈflʌktʃueɪt/", partOfSpeech: "v.", definitions: ["波动", "变化"], frequency: 47, difficulty: 4 },
    { word: "fundamental", phonetic: "/ˌfʌndəˈmentl/", partOfSpeech: "adj.", definitions: ["基本的", "根本的"], frequency: 48, difficulty: 3 },
    { word: "generate", phonetic: "/ˈdʒenəreɪt/", partOfSpeech: "v.", definitions: ["产生", "生成"], frequency: 49, difficulty: 3 },
    { word: "hypothesis", phonetic: "/haɪˈpɒθəsɪs/", partOfSpeech: "n.", definitions: ["假设", "前提"], frequency: 50, difficulty: 4 },
  ],

  // ═══════════════════════════════════════════════════════
  // 考研英语高频核心 50 词
  // ═══════════════════════════════════════════════════════
  kaoyan: [
    { word: "abundant", phonetic: "/əˈbʌndənt/", partOfSpeech: "adj.", definitions: ["丰富的", "充裕的"], frequency: 1, difficulty: 3 },
    { word: "accelerate", phonetic: "/əkˈseləreɪt/", partOfSpeech: "v.", definitions: ["加速", "促进"], frequency: 2, difficulty: 3 },
    { word: "acclaim", phonetic: "/əˈkleɪm/", partOfSpeech: "v./n.", definitions: ["称赞", "欢呼"], frequency: 3, difficulty: 4 },
    { word: "accommodate", phonetic: "/əˈkɒmədeɪt/", partOfSpeech: "v.", definitions: ["容纳", "适应"], frequency: 4, difficulty: 3 },
    { word: "accountable", phonetic: "/əˈkaʊntəbl/", partOfSpeech: "adj.", definitions: ["负有责任的"], frequency: 5, difficulty: 4 },
    { word: "advocate", phonetic: "/ˈædvəkeɪt/", partOfSpeech: "v./n.", definitions: ["拥护", "提倡者"], frequency: 6, difficulty: 3 },
    { word: "alleviate", phonetic: "/əˈliːvieɪt/", partOfSpeech: "v.", definitions: ["缓解", "减轻"], frequency: 7, difficulty: 4 },
    { word: "ambivalent", phonetic: "/æmˈbɪvələnt/", partOfSpeech: "adj.", definitions: ["矛盾的", "好恶交替的"], frequency: 8, difficulty: 5 },
    { word: "anonymous", phonetic: "/əˈnɒnɪməs/", partOfSpeech: "adj.", definitions: ["匿名的"], frequency: 9, difficulty: 3 },
    { word: "appreciable", phonetic: "/əˈpriːʃəbl/", partOfSpeech: "adj.", definitions: ["可察觉的", "相当数量的"], frequency: 10, difficulty: 4 },
    { word: "arouse", phonetic: "/əˈraʊz/", partOfSpeech: "v.", definitions: ["唤起", "引起"], frequency: 11, difficulty: 3 },
    { word: "ascribe", phonetic: "/əˈskraɪb/", partOfSpeech: "v.", definitions: ["归因于"], frequency: 12, difficulty: 4 },
    { word: "assert", phonetic: "/əˈsɜːrt/", partOfSpeech: "v.", definitions: ["断言", "维护"], frequency: 13, difficulty: 3 },
    { word: "attribute", phonetic: "/əˈtrɪbjuːt/", partOfSpeech: "v./n.", definitions: ["归因", "属性"], frequency: 14, difficulty: 3 },
    { word: "augment", phonetic: "/ɔːɡˈment/", partOfSpeech: "v.", definitions: ["增加", "扩大"], frequency: 15, difficulty: 4 },
    { word: "behold", phonetic: "/bɪˈhoʊld/", partOfSpeech: "v.", definitions: ["看到", "注视"], frequency: 16, difficulty: 4 },
    { word: "bewilder", phonetic: "/bɪˈwɪldər/", partOfSpeech: "v.", definitions: ["使迷惑"], frequency: 17, difficulty: 4 },
    { word: "bluff", phonetic: "/blʌf/", partOfSpeech: "v./n.", definitions: ["虚张声势"], frequency: 18, difficulty: 4 },
    { word: "boast", phonetic: "/boʊst/", partOfSpeech: "v.", definitions: ["夸耀", "拥有"], frequency: 19, difficulty: 3 },
    { word: "capture", phonetic: "/ˈkæptʃər/", partOfSpeech: "v.", definitions: ["俘获", "捕获"], frequency: 20, difficulty: 2 },
    { word: "cherish", phonetic: "/ˈtʃerɪʃ/", partOfSpeech: "v.", definitions: ["珍爱", "怀有"], frequency: 21, difficulty: 3 },
    { word: "circulate", phonetic: "/ˈsɜːrkjəleɪt/", partOfSpeech: "v.", definitions: ["流通", "循环"], frequency: 22, difficulty: 3 },
    { word: "condemn", phonetic: "/kənˈdem/", partOfSpeech: "v.", definitions: ["谴责", "判刑"], frequency: 23, difficulty: 3 },
    { word: "confine", phonetic: "/kənˈfaɪn/", partOfSpeech: "v.", definitions: ["限制", "禁闭"], frequency: 24, difficulty: 3 },
    { word: "conform", phonetic: "/kənˈfɔːrm/", partOfSpeech: "v.", definitions: ["遵守", "符合"], frequency: 25, difficulty: 3 },
    { word: "consolidate", phonetic: "/kənˈsɒlɪdeɪt/", partOfSpeech: "v.", definitions: ["巩固", "合并"], frequency: 26, difficulty: 4 },
    { word: "constitute", phonetic: "/ˈkɒnstɪtuːt/", partOfSpeech: "v.", definitions: ["构成", "建立"], frequency: 27, difficulty: 3 },
    { word: "contemplate", phonetic: "/ˈkɒntəmpleɪt/", partOfSpeech: "v.", definitions: ["沉思", "考虑"], frequency: 28, difficulty: 4 },
    { word: "contemporary", phonetic: "/kənˈtempəreri/", partOfSpeech: "adj.", definitions: ["当代的", "同时代的"], frequency: 29, difficulty: 3 },
    { word: "contend", phonetic: "/kənˈtend/", partOfSpeech: "v.", definitions: ["竞争", "声称"], frequency: 30, difficulty: 4 },
    { word: "convict", phonetic: "/kənˈvɪkt/", partOfSpeech: "v.", definitions: ["判罪"], frequency: 31, difficulty: 4 },
    { word: "cope", phonetic: "/koʊp/", partOfSpeech: "v.", definitions: ["应付", "处理"], frequency: 32, difficulty: 2 },
    { word: "correspond", phonetic: "/ˌkɒrəˈspɒnd/", partOfSpeech: "v.", definitions: ["符合", "通信"], frequency: 33, difficulty: 3 },
    { word: "corrupt", phonetic: "/kəˈrʌpt/", partOfSpeech: "adj./v.", definitions: ["腐败的", "贿赂"], frequency: 34, difficulty: 3 },
    { word: "decline", phonetic: "/dɪˈklaɪn/", partOfSpeech: "v./n.", definitions: ["下降", "拒绝"], frequency: 35, difficulty: 2 },
    { word: "dedicate", phonetic: "/ˈdedɪkeɪt/", partOfSpeech: "v.", definitions: ["奉献", "致力于"], frequency: 36, difficulty: 3 },
    { word: "deliberate", phonetic: "/dɪˈlɪbərət/", partOfSpeech: "adj.", definitions: ["深思熟虑的", "故意的"], frequency: 37, difficulty: 3 },
    { word: "denote", phonetic: "/dɪˈnoʊt/", partOfSpeech: "v.", definitions: ["表示", "意味着"], frequency: 38, difficulty: 4 },
    { word: "deprive", phonetic: "/dɪˈpraɪv/", partOfSpeech: "v.", definitions: ["剥夺"], frequency: 39, difficulty: 3 },
    { word: "derive", phonetic: "/dɪˈraɪv/", partOfSpeech: "v.", definitions: ["源于", "得出"], frequency: 40, difficulty: 3 },
    { word: "desperate", phonetic: "/ˈdespərət/", partOfSpeech: "adj.", definitions: ["绝望的", "拼命的"], frequency: 41, difficulty: 3 },
    { word: "deteriorate", phonetic: "/dɪˈtɪriəreɪt/", partOfSpeech: "v.", definitions: ["恶化"], frequency: 42, difficulty: 4 },
    { word: "diminish", phonetic: "/dɪˈmɪnɪʃ/", partOfSpeech: "v.", definitions: ["减少", "缩小"], frequency: 43, difficulty: 3 },
    { word: "discern", phonetic: "/dɪˈsɜːrn/", partOfSpeech: "v.", definitions: ["察觉", "辨别"], frequency: 44, difficulty: 4 },
    { word: "disclose", phonetic: "/dɪsˈkloʊz/", partOfSpeech: "v.", definitions: ["透露", "揭示"], frequency: 45, difficulty: 3 },
    { word: "dispute", phonetic: "/dɪˈspjuːt/", partOfSpeech: "n./v.", definitions: ["争论", "争议"], frequency: 46, difficulty: 3 },
    { word: "disrupt", phonetic: "/dɪsˈrʌpt/", partOfSpeech: "v.", definitions: ["扰乱", "中断"], frequency: 47, difficulty: 3 },
    { word: "distract", phonetic: "/dɪˈstrækt/", partOfSpeech: "v.", definitions: ["分散注意", "使分心"], frequency: 48, difficulty: 3 },
    { word: "diverge", phonetic: "/daɪˈvɜːrdʒ/", partOfSpeech: "v.", definitions: ["分歧", "分开"], frequency: 49, difficulty: 4 },
    { word: "dwell", phonetic: "/dwel/", partOfSpeech: "v.", definitions: ["居住", "细想"], frequency: 50, difficulty: 3 },
  ],

  // 雅思/托福/GRE 留空，让用户用扩展词库功能 AI 生成
  ielts: [],
  toefl: [],
  gre: [],
};